import { contextBridge, ipcRenderer } from 'electron';
import { AppSettings, BannerItem, ConnectionState, EnvCheckResult } from './shared/types';

contextBridge.exposeInMainWorld('api', {
  envCheck: (): Promise<EnvCheckResult[]> => ipcRenderer.invoke('env:check'),
  install: (): Promise<{ ok: boolean; installDir?: string; error?: string }> => ipcRenderer.invoke('app:install'),
  onInstallProgress: (cb: (data: { percent: number; text: string }) => void) => ipcRenderer.on('install:progress', (_event, data) => cb(data)),
  setAutostart: (enabled: boolean): Promise<boolean> => ipcRenderer.invoke('installer:set-autostart', enabled),
  getAutostart: (): Promise<boolean> => ipcRenderer.invoke('installer:get-autostart'),
  finishInstall: (): Promise<void> => ipcRenderer.invoke('installer:finish'),
  getSettings: (): Promise<AppSettings> => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings: AppSettings): Promise<AppSettings> => ipcRenderer.invoke('settings:set', settings),
  resetSettings: (): Promise<AppSettings> => ipcRenderer.invoke('settings:reset'),
  openExternal: (url: string): Promise<void> => ipcRenderer.invoke('shell:open', url),
  onBannerShow: (cb: (item: BannerItem) => void) => ipcRenderer.on('banner:show', (_event, item: BannerItem) => cb(item)),
  onBannerMeasure: (cb: (item: BannerItem) => void) => ipcRenderer.on('banner:measure', (_event, item: BannerItem) => cb(item)),
  onBannerRemove: (cb: (id: string) => void) => ipcRenderer.on('banner:remove', (_event, id: string) => cb(id)),
  reportHeight: (id: string, height: number) => ipcRenderer.send('banner:height', { id, height }),
  onBannerConfig: (cb: (config: { fontSize: number; opacity: number; width: number; bgColor?: string; labelColor?: string; nickColor?: string; textColor?: string }) => void) => ipcRenderer.on('banner:config', (_event, config) => cb(config)),
  onConnectionState: (cb: (state: ConnectionState) => void) => ipcRenderer.on('connection:state', (_event, state: ConnectionState) => cb(state)),
  onQqAccount: (cb: (info: { userId: number | null; nickname: string }) => void) => ipcRenderer.on('qq:account', (_event, info) => cb(info)),
  onWechatState: (cb: (info: { state: string; message: string; loggedIn: boolean; selfWxid?: string; nickname?: string }) => void) => ipcRenderer.on('wechat:state', (_event, info) => cb(info)),
  trayGetVisibility: (): Promise<boolean> => ipcRenderer.invoke('tray:get-visibility'),
  trayToggle: (): Promise<boolean> => ipcRenderer.invoke('tray:toggle'),
  trayQuit: (): Promise<void> => ipcRenderer.invoke('tray:quit'),
  trayUninstallOpen: (): Promise<void> => ipcRenderer.invoke('tray:uninstall-open'),
  trayUninstallCancel: (): Promise<void> => ipcRenderer.invoke('tray:uninstall-cancel'),
  trayUninstallConfirm: (): Promise<void> => ipcRenderer.invoke('tray:uninstall-confirm'),
  trayRefresh: (): Promise<boolean> => ipcRenderer.invoke('tray:refresh'),
  trayOpenConsole: (): Promise<void> => ipcRenderer.invoke('tray:open-console'),
  onTrayVisibility: (cb: (visible: boolean) => void) => ipcRenderer.on('tray:visibility', (_event, visible: boolean) => cb(visible)),
  trayGetScope: (): Promise<{ scopeSpecialPrivate: boolean; scopeNormalPrivate: boolean; scopeNormalGroup: boolean; wechatPrivate: boolean; wechatGroup: boolean }> => ipcRenderer.invoke('tray:get-scope'),
  traySetScope: (patch: { scopeSpecialPrivate?: boolean; scopeNormalPrivate?: boolean; scopeNormalGroup?: boolean; wechatPrivate?: boolean; wechatGroup?: boolean }): Promise<{ scopeSpecialPrivate: boolean; scopeNormalPrivate: boolean; scopeNormalGroup: boolean; wechatPrivate: boolean; wechatGroup: boolean }> => ipcRenderer.invoke('tray:set-scope', patch),
  traySubmenuShow: (kind: string, top: number): void => ipcRenderer.send('tray:submenu-show', { kind, top }),
  onTraySubmenuData: (cb: (data: { kind: 'qq' | 'wechat'; scope: { scopeSpecialPrivate: boolean; scopeNormalPrivate: boolean; scopeNormalGroup: boolean; wechatPrivate: boolean; wechatGroup: boolean } }) => void) => ipcRenderer.on('tray:submenu-data', (_event, data) => cb(data)),
  getLanguage: (): Promise<'zh' | 'en'> => ipcRenderer.invoke('i18n:get-language'),
  setLanguage: (lang: 'zh' | 'en'): Promise<'zh' | 'en'> => ipcRenderer.invoke('i18n:set-language', lang),
  getMessages: (lang: 'zh' | 'en'): Promise<Record<string, string>> => ipcRenderer.invoke('i18n:get-messages', lang),
  onLanguageChanged: (cb: (lang: 'zh' | 'en') => void) => ipcRenderer.on('i18n:changed', (_event, lang: 'zh' | 'en') => cb(lang))
});
